# Generated by Django 3.1.6 on 2021-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bond_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
